# Generated by Django 5.2.17 on 2026-08-12 05:29

import vinta_billing.registry
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ``vinta-django-orgs`` 0.2.0 renamed both apps and collapsed each one's
        # migrations into a single ``0001_initial`` under the new label, so this
        # names that rather than the pre-rename leaf it was generated against.
        ("vinta_orgs", "0001_initial"),
        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                ("street_name", models.TextField()),
                ("street_number", models.TextField()),
                ("neighborhood", models.TextField(blank=True)),
                ("address_line_2", models.TextField(blank=True)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BillingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_default_for_new_organizations",
                    models.BooleanField(default=False),
                ),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "annual_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "grace_period_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default_for_new_organizations", True)),
                        fields=("is_default_for_new_organizations",),
                        name="uniq_default_billing_plan",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BillingProfile",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="billing_profile",
                        serialize=False,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                ("contact_first_name", models.CharField(max_length=255)),
                ("contact_last_name", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CPF", "CPF"),
                            ("CNPJ", "CNPJ"),
                            ("DNI", "DNI"),
                            ("CI", "CI"),
                            ("RUT", "RUT"),
                            ("SSN", "SSN"),
                            ("EIN", "EIN"),
                            ("PASSPORT", "Passport"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("document_number", models.CharField(max_length=50)),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        choices=[("mercadopago", "MercadoPago"), ("stripe", "Stripe")],
                        default="",
                        max_length=50,
                    ),
                ),
                (
                    "billing_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_profile",
                        to="vinta_billing.billingaddress",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=50)),
                (
                    "payment_provider",
                    models.CharField(
                        choices=[("mercadopago", "MercadoPago"), ("stripe", "Stripe")],
                        max_length=50,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_send", "Pending send"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("partially_refunded", "Partially refunded"),
                            ("refunded", "Refunded"),
                            ("charged_back", "Charged back"),
                            ("in_process", "In process"),
                            ("in_mediation", "In mediation"),
                            ("rejected_by_bank", "Rejected by bank"),
                            ("expired", "Expired"),
                            ("unknown", "Unknown"),
                            ("error", "Error"),
                        ],
                        max_length=50,
                    ),
                ),
                ("original_status", models.CharField(max_length=50)),
                ("payment_method", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "billing_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing",
                        to="vinta_billing.billingprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentStatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_send", "Pending send"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("partially_refunded", "Partially refunded"),
                            ("refunded", "Refunded"),
                            ("charged_back", "Charged back"),
                            ("in_process", "In process"),
                            ("in_mediation", "In mediation"),
                            ("rejected_by_bank", "Rejected by bank"),
                            ("expired", "Expired"),
                            ("unknown", "Unknown"),
                            ("error", "Error"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="vinta_billing.payment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("mercadopago", "MercadoPago"), ("stripe", "Stripe")],
                        max_length=50,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("payment_update", "Payment update"),
                            (
                                "subscription_payment_update",
                                "Subscription payment update",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("external_event_id", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "route", "external_event_id"),
                        name="uniq_provider_webhook_event",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=50)),
                ("external_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_send", "Pending Send"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                            ("unknown", "Unknown"),
                        ],
                        default="pending_send",
                        max_length=50,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="vinta_billing.payment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RefundStatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_send", "Pending Send"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                (
                    "refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="vinta_billing.refund",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending"),
                            ("pending_send", "Pending send"),
                            ("error", "Error"),
                            ("unknown", "Unknown"),
                        ],
                        default="pending_send",
                        max_length=50,
                    ),
                ),
                (
                    "billing_state",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("active", "Active"),
                            ("grace", "Grace period"),
                            ("restricted", "Restricted"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField(db_index=True)),
                (
                    "grace_period_ends_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "last_dunning_attempt_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("plan_external_id", models.CharField(blank=True, max_length=255)),
                (
                    "payment_provider",
                    models.CharField(
                        choices=[("mercadopago", "MercadoPago"), ("stripe", "Stripe")],
                        max_length=50,
                    ),
                ),
                (
                    "pending_billing_interval",
                    models.CharField(
                        blank=True,
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        max_length=10,
                    ),
                ),
                (
                    "pending_plan_effective_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "plan_change_pending_confirmation",
                    models.BooleanField(default=False),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "pending_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="vinta_billing.billingplan",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="vinta_billing.billingplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing",
                to="vinta_billing.subscription",
            ),
        ),
        migrations.CreateModel(
            name="BillingPeriodSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                ("billing_period_start", models.DateTimeField(db_index=True)),
                ("billing_period_end", models.DateTimeField()),
                ("plan_slug", models.CharField(max_length=100)),
                ("plan_name", models.CharField(max_length=255)),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("overage_total", models.DecimalField(decimal_places=4, max_digits=12)),
                ("charged", models.BooleanField()),
                ("reconciliation_unmetered", models.PositiveIntegerField()),
                ("reconciliation_orphaned", models.PositiveIntegerField()),
                ("closed_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_period_summaries",
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="period_summaries",
                        to="vinta_billing.payment",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_summaries",
                        to="vinta_billing.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ("-billing_period_start",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubscriptionAddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "resource_key",
                    models.CharField(
                        choices=vinta_billing.registry.resource_choices, max_length=100
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("is_recurring", models.BooleanField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                (
                    "purchase_idempotency_key",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="add_on",
                        to="vinta_billing.payment",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="add_ons",
                        to="vinta_billing.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubscriptionEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "entitlement_key",
                    models.CharField(
                        choices=vinta_billing.registry.entitlement_choices, max_length=100
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("is_overridden", models.BooleanField(default=False)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to="vinta_billing.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlanLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "resource_key",
                    models.CharField(
                        choices=vinta_billing.registry.resource_choices, max_length=100
                    ),
                ),
                ("limit_value", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("prepaid", "Prepaid"), ("postpaid", "Postpaid")],
                        max_length=20,
                    ),
                ),
                (
                    "overage_unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("is_overridden", models.BooleanField(default=False)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limits",
                        to="vinta_billing.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubscriptionStatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending"),
                            ("pending_send", "Pending send"),
                            ("error", "Error"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="vinta_billing.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BillingPeriodResourceUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "resource_key",
                    models.CharField(
                        choices=vinta_billing.registry.resource_choices, max_length=100
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[("prepaid", "Prepaid"), ("postpaid", "Postpaid")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("total", models.PositiveIntegerField(blank=True, null=True)),
                ("limit_value", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "overage_unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("by_organization", models.JSONField(default=dict)),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="vinta_billing.billingperiodsummary",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("summary", "resource_key"),
                        name="uniq_billing_period_resource_usage",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("mercadopago", "MercadoPago"), ("stripe", "Stripe")],
                        max_length=50,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "provider", "external_id"),
                        name="uniq_payment_method",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "entitlement_key",
                    models.CharField(
                        choices=vinta_billing.registry.entitlement_choices, max_length=100
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to="vinta_billing.billingplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "entitlement_key"),
                        name="uniq_plan_entitlement_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "resource_key",
                    models.CharField(
                        choices=vinta_billing.registry.resource_choices, max_length=100
                    ),
                ),
                ("limit_value", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("prepaid", "Prepaid"), ("postpaid", "Postpaid")],
                        max_length=20,
                    ),
                ),
                (
                    "overage_unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limits",
                        to="vinta_billing.billingplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "resource_key"), name="uniq_plan_limit_resource"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MeteredOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                ("event_id", models.BigIntegerField()),
                ("occurrence_start", models.DateTimeField()),
                ("billing_period_start", models.DateTimeField(db_index=True)),
                ("is_within_allowance", models.BooleanField()),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metered_occurrences",
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metered_occurrences",
                        to="vinta_billing.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["subscription", "billing_period_start"],
                        name="metered_occ_sub_period_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "event_id", "occurrence_start"),
                        name="uniq_metered_occurrence",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LimitWarningNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                (
                    "resource_key",
                    models.CharField(
                        choices=vinta_billing.registry.resource_choices, max_length=100
                    ),
                ),
                ("billing_period_start", models.DateTimeField(db_index=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("approaching", "Approaching the limit"),
                            ("reached", "At or over the limit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limit_warnings",
                        to="vinta_billing.subscription",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "subscription",
                            "resource_key",
                            "billing_period_start",
                            "level",
                        ),
                        name="uniq_limit_warning_notification",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="billingperiodsummary",
            index=models.Index(
                fields=["organization", "-billing_period_start"],
                name="billing_period_org_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingperiodsummary",
            constraint=models.UniqueConstraint(
                fields=("subscription", "billing_period_start"),
                name="uniq_billing_period_summary",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionentitlement",
            constraint=models.UniqueConstraint(
                fields=("subscription", "entitlement_key"),
                name="uniq_sub_entitlement_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplanlimit",
            constraint=models.UniqueConstraint(
                fields=("subscription", "resource_key"), name="uniq_sub_limit_resource"
            ),
        ),
    ]
