# Generated by Django 5.2.17 on 2026-08-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vinta_billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "permissions": [
                    ("manage_billing", "Can manage the organization's billing")
                ]
            },
        ),
    ]
