"""Both swapped-in scope models, in one migration.

Only one of them has a table under any given settings module: the other is
swapped out, and Django skips creating it. That is what lets
``tests.settings_scope_swapped`` and ``tests.settings_mixed`` share this app.
"""

# Generated by Django 5.2.17 on 2026-09-09 05:28

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # `testapp.0001`, not `0002`: the payer table is all this app needs, and
        # 0002 is the one that points *back* at the scope model. Depending on it
        # would close the cycle `testapp -> swapped_scopes -> testapp`.
        ("testapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MixedScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                ("scope_type", models.CharField(default="organization", max_length=32)),
                ("scope_key", models.CharField(db_index=True, max_length=255)),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_billing_scopes",
                        to="testapp.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_children",
                        # The concrete model, not the setting: a scope's parent
                        # is always its own class. See the field's comment in
                        # `vinta_billing.models.AbstractBillingScope`.
                        to="swapped_scopes.mixedscope",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personal_billing_scopes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "BILLING_SCOPE_MODEL",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("company__isnull", True), ("user__isnull", False)
                            ),
                            models.Q(
                                ("company__isnull", False), ("user__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="mixed_scope_is_exactly_one_payer",
                    ),
                    models.UniqueConstraint(
                        fields=("scope_type", "scope_key"),
                        name="mixed_scope_unique_key_per_type",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(blank=True, default=dict, verbose_name="meta"),
                ),
                ("scope_type", models.CharField(default="organization", max_length=32)),
                ("scope_key", models.CharField(db_index=True, max_length=255)),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_scopes",
                        to="testapp.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_children",
                        # The concrete model, not the setting: a scope's parent
                        # is always its own class. See the field's comment in
                        # `vinta_billing.models.AbstractBillingScope`.
                        to="swapped_scopes.companyscope",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "BILLING_SCOPE_MODEL",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope_type", "scope_key"),
                        name="company_scope_unique_key_per_type",
                    )
                ],
            },
        ),
    ]
