# Generated by Django 5.2.17 on 2026-08-12 05:29

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.ORGANIZATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testapp_seats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["organization", "id"],
                        name="testapp_sea_organiz_7364a1_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SeatInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["organization", "id"],
                        name="testapp_sea_organiz_280e2c_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ORGANIZATION_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "original_manager",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["organization", "id"],
                        name="testapp_wid_organiz_ad78e7_idx",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("original_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
